### ISSUE TITLE
Preload our extensions

### ISSUE THREAD

**Issue by DavidLeoni** [CoderDojoTrento/botch-gui#3]
When the user enters the editor, having the extension preloaded avoids manually clicking around to enable it

**Comment by raffaelepojer** [comment]
Committed in botch-vm
commit 0e5d3deb8c5815606ee721f12995f77ebaceb8a4
[here](https://github.com/CoderDojoTrento/botch-vm/commit/0e5d3deb8c5815606ee721f12995f77ebaceb8a4)
