### ISSUE TITLE
Add supersimple tutorial

### ISSUE THREAD

**Issue by DavidLeoni** [CoderDojoTrento/botch-gui#5]
When Evoscratch loads, a tutorial explaining first steps should appear.

For Milestone 0.1, we can add a super simple tutorial which just shows we learnt how to do tutorials :-) 
It could have a couple of slides about what EvoScratch is supposed to do (don't need videos for now).

Important things to remind users:

- projects created in EvoScratch will not load in official Scratch
- to save projects you need to do File->Download to your computer / Load from your computer
- big red warn that for versions < 1.0  actual capability to reload file is NOT guaranteed, use-at-your-own-risk

**Comment by raffaelepojer** [comment]
To load a tutorial on startup
[https://github.com/LLK/scratch-gui/issues/3138](https://github.com/LLK/scratch-gui/issues/3138)

**Comment by DavidLeoni** [comment]
We have tutorial sample in botch-0.2, I'm closing this issue. For the real tutorial, I'll create another issue.
